FROM node:18 AS build


ARG REACT_APP_STRAPI_AUTH_TOKEN
ENV REACT_APP_STRAPI_AUTH_TOKEN $REACT_APP_STRAPI_AUTH_TOKEN

ARG REACT_APP_STRAPI_URL
ENV REACT_APP_STRAPI_URL $REACT_APP_STRAPI_URL

WORKDIR /app
COPY package*.json ./
RUN npm rebuild node-sass
RUN yarn
COPY . ./

RUN yarn build

# Stage 2: Serve the React application with Nginx
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]