FROM node:16-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm rebuild node-sass
RUN yarn
COPY . ./
RUN yarn build
RUN npm i -g serve


EXPOSE 3000
CMD ["serve", '-l', "3000" ,"-s", "build"]  