FROM node:16-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm rebuild node-sass
RUN yarn
COPY . ./

RUN yarn build

# Stage 2: Serve the React application with Nginx
FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]