version: "3"

services:
  gettem:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
       - ./frontend:/gettem
       - /node_modules
    environment:
       - CHOKIDAR_USEPOLLING=true
    command: sh -c "
        npm rebuild node-sass
        && yarn; yarn start
      "

  strapi:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: gettem
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: juna
      DATABASE_PASSWORD: gettem
    volumes:
      - ./backend:/app
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: gettem
      POSTGRES_USER: juna
      POSTGRES_DB: gettem
    volumes:
      - ./pgdata:/var/lib/postgresql/data