# https://medium.com/trabe/map-subdomains-to-docker-containers-with-traefik-efd6aa66e073
version: "3"

services:

  gettem:
    image: otacon900/gettem:latest
    environment: 
      REACT_APP_STRAPI_URL: ${STRAPI_URL}
      REACT_APP_STRAPI_AUTH_TOKEN: ${STRAPI_AUTH_TOKEN}
    deploy:
      resources:
        limits:
          cpus: '0.1'  # Maximum number of CPUs (can be fractional)
          memory: 20M # Maximum memory (M for Megabytes, G for Gigabytes)
        reservations:
          cpus: '0.1'  # Maximum number of CPUs (can be fractional)
          memory: 20M # Maximum memory (M for Megabytes, G for Gigabytes)
    container_name: "gettem"
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gettem.rule=Host(`joneid.dev`)"
      - "traefik.http.routers.gettem.entrypoints=websecure"
      - "traefik.http.services.gettem.loadbalancer.server.port=3000"
      - "traefik.http.routers.gettem.tls.certresolver=myresolver"

  strapi:
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    deploy:
      resources:
        limits:
          cpus: '0.3'  # Maximum number of CPUs (can be fractional)
          memory: 200M # Maximum memory (M for Megabytes, G for Gigabytes)
        reservations:
          cpus: '0.3'  # Maximum number of CPUs (can be fractional)
          memory: 200M # Maximum memory (M for Megabytes, G for Gigabytes)
    container_name: "strapi"
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: gettem
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASS}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      URL: ${STRAPI_URL}
    volumes:
      - ./backend:/app
    ports:
      - "1337:1337"
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.strapi.rule=Host(`dashboard.joneid.dev`)"
      - "traefik.http.routers.strapi.entrypoints=websecure"
      - "traefik.http.services.strapi.loadbalancer.server.port=1337"
      - "traefik.http.routers.strapi.tls.certresolver=myresolver"


  postgres:
    image: postgres
    deploy:
      resources:
        limits:
          cpus: '0.2'  # Maximum number of CPUs (can be fractional)
          memory: 200M # Maximum memory (M for Megabytes, G for Gigabytes)
        reservations:
          cpus: '0.2'  # Maximum number of CPUs (can be fractional)
          memory: 200M # Maximum memory (M for Megabytes, G for Gigabytes)
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: gettem
    volumes:
      - ./pgdata:/var/lib/postgresql/data


  traefik:
    image: "traefik:v2.10"
    deploy:
      resources:
        limits:
          cpus: '0.2'  # Maximum number of CPUs (can be fractional)
          memory: 50M # Maximum memory (M for Megabytes, G for Gigabytes)
        reservations:
          cpus: '0.2'  # Maximum number of CPUs (can be fractional)
          memory: 50M # Maximum memory (M for Megabytes, G for Gigabytes)
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=jonathaneid98@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
