name: Traefik Reverse-Proxy

# This workflow triggers whenever there's a push to the 'prod' branch. 
on:
    workflow_dispatch:

jobs:
  job_id:
    environment:
      name: production
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
    - uses: 'actions/checkout@v4'
    - name: print oidc token claims
      run: |
          IDTOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" -H "Accept: application/json; api-version=2.0" -H "Content-Type: application/json"  | jq -r '.value')
          jwtd() {
            if [[ -x $(command -v jq) ]]; then
                jq -R 'split(".") | .[1] | @base64d | fromjson' <<< "${1}" > jwt_claims.json
                cat jwt_claims.json
                echo ${{ env.ACTIONS_ID_TOKEN_REQUEST_URL}} 
            fi
          }
          jwtd $IDTOKEN

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/527783132744/locations/global/workloadIdentityPools/gettem-github/providers/github'
        service_account: 'gettem-github-actions@portfolio-website-414517.iam.gserviceaccount.com'


    - id: 'ls-ssh'
      uses: 'google-github-actions/ssh-compute@v1'
      continue-on-error: true
      with:
        instance_name: 'instance-20240216-171943'
        zone: 'us-central1-a'
        user: 'github'
        ssh_private_key: '${{ secrets.GCP_SSH }}'
        command: ls

    - id: 'compute-ls'
      uses: 'google-github-actions/ssh-compute@v1'
      continue-on-error: true
      with:
        instance_name: 'instance-20240216-171943'
        zone: 'us-central1-a'
        user: 'github'
        ssh_private_key: '${{ secrets.GCP_SSH }}'
        command: ls ~/gettem

    - id: 'git-update'
      uses: 'google-github-actions/ssh-compute@v1'
      continue-on-error: true
      with:
        instance_name: 'instance-20240216-171943'
        zone: 'us-central1-a'
        user: 'github'
        ssh_private_key: '${{ secrets.GCP_SSH }}'
        command: "cd ~/gettem; git fetch origin prod; git reset --hard FETCH_HEAD; git clean -df"

    - id: 'compute-ssh'
      uses: 'google-github-actions/ssh-compute@v1'
      continue-on-error: true
      with:
        instance_name: 'instance-20240216-171943'
        zone: 'us-central1-a'
        user: 'github'
        ssh_private_key: '${{ secrets.GCP_SSH }}'
        script: ~/gettem/traefik.sh
          

    # Example of using the output
    - id: 'test'
      run: |-
        echo '${{ steps.ls-ssh.outputs.stdout }}'
        echo '${{ steps.ls-ssh.outputs.stderr }}'
    - id: 'test1'
      run: |-
        echo '${{ steps.compute-ls.outputs.stdout }}'
        echo '${{ steps.compute-ls.outputs.stderr }}'
    - id: 'test2'
      run: |-
        echo '${{ steps.git-update.outputs.stdout }}'
        echo '${{ steps.git-update.outputs.stderr }}'
    - id: 'test3'
      run: |-
        echo '${{ steps.compute-ssh.outputs.stdout }}'
        echo '${{ steps.compute-ssh.outputs.stderr }}'
